### ISSUE TITLE
Integer Accepted for Seed in both Digger and Rockstart minigames

### ISSUE THREAD

**Issue by syed-razi** [BryanChiu/Mactivision#101]
### Description:
I noticed that setting the Seed to an integer works just like a string. This does not seem to be intended from the instructions on editing the configuration file:

![image](https://user-images.githubusercontent.com/25377291/110270433-cb243580-7f93-11eb-958b-6e4eb7a07c50.png)

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open Battery.json
2. Set Seed under FeederConfig and RockstarConfig to `10`
![image](https://user-images.githubusercontent.com/25377291/110270632-41289c80-7f94-11eb-8199-822c2770fffe.png)

3. Save file
3. Start Client and Server
4. Play normally

### Actual Result:

There seems to be no impact on the game, nor any error message

### Expected Result:

I would have expected this to fail or to get some sort of warning, or for the instructions to mention that integers are allowed

### Severity: Low

**Comment by BryanChiu** [comment]
This is working as intended; the game will cast any value to the intended type (in this case the integer 10 is cast to a string "10")
