### ISSUE TITLE
Digger game extreme lag

### ISSUE THREAD

**Issue by nikhail-singh** [BryanChiu/Mactivision#102]
# issue: 
digger game with default settings has serious lag between audio and visual. This was not present when tested on firefox

# browser and operating system:
Chrome on windows 10

# steps to reproduce:
1.  run client.py
2.  run server.py
3. navigate to localhost:3000 in chrome
4.  Run the battery.
5. Play the digger game

**Comment by DavidHospital** [comment]
We are not able to reproduce this issue, so it will be closed

**Comment by BryanChiu** [comment]
Playing on Chrome with hardware acceleration off results in laggy play
