### ISSUE TITLE
Rockstar - Can Set Left, Right, and Firework Action to the same Key

### ISSUE THREAD

**Issue by syed-razi** [BryanChiu/Mactivision#103]
### Description:
I noticed that nothing prevents me from choosing the same key for the left, right, and firework function for the rockstar minigame. The result is that I am unable to move the spotlight and only able to increase the meter on the right

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open Battery.json
2. Set LeftKey, RightKey, and UpKey to `"A"`
![image](https://user-images.githubusercontent.com/25377291/110271329-ce202580-7f95-11eb-8078-f114c9ec8179.png)
3. Start Client and Server
4. Play through to Rockstart game
5. Try moving spotlight

### Actual Result:

Able to set LeftKey, RightKey, and UpKey to "A" without any warning or error

### Expected Result:

I would expect that it would not be allowed to set multiple functions to the same key.

### Suggestion

Make it not possible to set multiple functions to the same key

**Comment by BryanChiu** [comment]
Will check to see if same keys are being used and if so, console outputs warning that same keys are being used.
