### ISSUE TITLE
Rockstar -  can complete without ever using the "L" key

### ISSUE THREAD

**Issue by nikhail-singh** [BryanChiu/Mactivision#104]
Issue: Can complete the entire game without ever using the fireworks and still get the "what a great show" message

Browser and OS: Firefox on windows 10

Steps to reproduce:
1. launch the game
2. get to the rockstar game
3. play the game only using the "A" and "D" keys and you'll still complete it despite audience hype being 0

**Comment by BryanChiu** [comment]
This is out of the scope of our project; the player cannot "lose". These minigames are meant to record a user's abilities.
