### ISSUE TITLE
Rockstar - Unclear Crowd Energy Level Meter

### ISSUE THREAD

**Issue by syed-razi** [BryanChiu/Mactivision#105]
### Description:
There seems to be two red zones for the crowd energy level which seems odd. The red zone at the bottom makes sense, indicating that the energy levels have dropped too low, but the red zone at the top does not, as it is expected to keep the energy levels high

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Start up client and server
2. Play minigames until you reach the Rockstart game

### Actual Result:

Notice two red zones for crowd energy level:
![image](https://user-images.githubusercontent.com/25377291/110274055-f01ca680-7f9b-11eb-83a3-91fc876e2f3c.png)

### Expected Result:

I would expected to only see a red zone at the bottom as per the game objectives

### Suggestion

Remove top red zone or explain it's purpose

**Comment by BryanChiu** [comment]
This was explained as "too many fireworks are dangerous". We don't want the user to just hold down the key. Also, these specific graphics were placeholder.
