### ISSUE TITLE
Feeding game: waster will sometimes give conflicting results for the same food

### ISSUE THREAD

**Issue by nikhail-singh** [BryanChiu/Mactivision#106]
# Issue: 
when playing the feeding minigame sometimes the same food will be green when put into the food waste but then will be red **without** that food showing up as a changed preference for the monster.

# Browser:
Firefox

# steps to reproduce
1. Play the feeding minigame
2. watch carefully for one type of food (e.g the green hamburger)
3. put the food into the food waste and note the colour
4. get the same food again (green hamburger again) **Before** the food preferences change
5. put it in the food waste again
6. See that the colour is different

**Comment by nikhail-singh** [comment]
I'm aware that when the preferences change this is expected but unless I missed something I don't believe this is correct if the preferences haven't changed.

**Comment by DavidHospital** [comment]
@nikhail-singh By any chance, would you be able to provide the config file used for this test, as well as the random seed reported in the `feeder_***.json`? It would greatly help us to reproduce this issue. Thanks

**Comment by DavidHospital** [comment]
Reporter never got back to us so we will close this issue.
