### ISSUE TITLE
Setting the key to a number causes the display to display press Alpha_ instead of that number

### ISSUE THREAD

**Issue by nikhail-singh** [BryanChiu/Mactivision#107]
Issue: when setting the keys for the games if you select a number key such as "1" using the appropriate unity code ("alpha1" for "1" for example) the game display shows press "Alpha 1" instead of just pressing "1"

Steps to reproduce:
1. Open the battery.json
2. change one of the keys such as Digkey to "alpha1" or any other unity number code
3. when the game instructions load it will show "Press "alpha1"..." instead of displaying the number

Expected behaviour:
to display the correct key to press (in this case the number associated with the unity key)

Screenshot
![image](https://user-images.githubusercontent.com/35268769/110274742-869d9780-7f9d-11eb-99b6-b741199220d5.png)

**Comment by BryanChiu** [comment]
We will only allow certain keys, and rename them properly
