### ISSUE TITLE
Feeding monster instruction confusion

### ISSUE THREAD

**Issue by Danielwu9226** [BryanChiu/Mactivision#108]
Perhaps leave the desired food on the screen or make it blinking, so users have better idea what we are actually feeding the monster.

Severity: Minor

**Comment by BryanChiu** [comment]
The point of the game is to remember the good/bad foods. Will update documentation to explain this is a memory test.

**Comment by BryanChiu** [comment]
[Game description](https://github.com/BryanChiu/Mactivision/blob/master/README.md) updated
