### ISSUE TITLE
Procedure confusion

### ISSUE THREAD

**Issue by Danielwu9226** [BryanChiu/Mactivision#109]
Steps to reproduce: 
This step is tedious, if we have step 8. 
6. client.py starts a server on 127.0.0.1:3000 > load client.py

Serverity: minor

**Comment by teemh** [comment]
We are able to move the in client.py into server.py so it should be less tedious now.

**Comment by DavidHospital** [comment]
Testable Artifact Instructions are outdated. Won't fix
