### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by Danielwu9226** [BryanChiu/Mactivision#110]
The initial screen does not allow user to press "Start Battery" every initialization, assuming failure to load libraries or errors or crashed. Perhaps make a clear indication of what to do when users run into this situation, instead of users blindly refreshing until it works.

**Comment by BryanChiu** [comment]
If a config file is not selected, user will not be able to start battery; is a config file selected? Please provide more information or reproduction steps. Network errors should appear in console.

**Comment by DavidHospital** [comment]
Reporter never got back to us so we will close this issue.
