### ISSUE TITLE
Client shows no response/errors on server close

### ISSUE THREAD

**Issue by anthonylou** [BryanChiu/Mactivision#111]
During the normal gameplay loop, closing the server will not affect the game in any way, and players can continue to play as normal. This may be troublesome during testing if the server were to crash or disconnect for any reason, causing data to be lost and the test to continue to run. 

**Steps to recreate:**
1. Run both the client/server, load into the Digger level
2. While digging, close the server. 

**Effects:** Player is able to continue and complete the minigames, and are presented with the end scene as if no errors occurred. In the "Output" folder, there are no created folders for the session.

**Comment by teemh** [comment]
If the server goes offline during a the Battery, the player will be moved to the start screen and be told that there is a network issue.
