### ISSUE TITLE
User ability metrics are missing/incomplete

### ISSUE THREAD

**Issue by anthonylou** [BryanChiu/Mactivision#113]
Within the created .json files for each level, there is a lot of raw data recorded, but not many user-specific metrics recorded. This may pose an issue as the project goal is to provide researchers with player data measuring user performance, and the data to derive such performance is missing (or requires further processing to attain).

Examples: 
- In the "Digger" level, there are no player-centric metrics such as keypresses per second, total presses, etc. It appears that events are created at a specific polling rate, so total elapsed time is also missing. 
- In the "Feeder" level, the data to calculate total correct answers is available, but is not easily accessible for researchers (depending on project context). Currently, each answer is split into its own event, and `choice` must be compared to `objectsSet` to determine if the answer is correct/incorrect. 
- The "Rockstar" level has no apparent useful metrics for research. Examples of such metrics could include:
    - Total rockstar illumination time, Illumination percentage
    - Fireworks rate, percentage of time spent in redzones
    - Player response time to rockstar moves

It seems that these (especially the "Rockstar" level) are still WIP, so hopefully the examples provided above may be helpful for future implementation. 

![Screenshot 2021-03-08 051338](https://user-images.githubusercontent.com/48287641/110307576-10188e00-7fcd-11eb-81a2-28b339309e38.png)

**Comment by BryanChiu** [comment]
Raw data dump without any calculations is intended
