### ISSUE TITLE
WebGL Warning

### ISSUE THREAD

**Issue by Wesley-Guoxy** [BryanChiu/Mactivision#114]
## Description
After I start running the two python script called “client.py” and “server.py”, I open up my browser and navigate to localhost:3000. Everything works fine until the main page is fully loaded, when I find several warnings about WebGL. Warning logs will be shown below.
## Environment
Windows10, Python3.7.9, Microsoft Edge version 89.0.774.45 (64-bit)
## Steps to Reproduce
1.	run python script client.py and server.py
2.	open up browser and visit localhost:3000
3.	press F12 and refresh the web page
4.	find warning logs in console panel
![image](https://user-images.githubusercontent.com/42874340/110311342-991bdd80-803e-11eb-8e7a-237585ca3d04.png)
## Expected Result
no warning logs expected
## Severity
LOW

**Comment by DavidHospital** [comment]
This is out of the scope of our project.
