### ISSUE TITLE
Shader Error

### ISSUE THREAD

**Issue by Wesley-Guoxy** [BryanChiu/Mactivision#116]
## Description:
When I start to play the first mini game, I notice that console continuously logging error message. I think these error messages are involved with PC GPU model type. In addition, my computer only have a AMD Ryzen 4800U CPU and I don’t have any independent GPU device. 

## Environment:
Windows10, Python3.7.9, Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:
![image](https://user-images.githubusercontent.com/42874340/110311897-60303880-803f-11eb-8a48-8a4a5aa79a1c.png)
![image](https://user-images.githubusercontent.com/42874340/110311908-62929280-803f-11eb-9c3e-e4e9c8b35aca.png)

## Expected Result:
No error logging messages in console

## Severity: 
LOW

**Comment by DavidHospital** [comment]
This is out of the scope of our project.
