### ISSUE TITLE
Advice for UI design

### ISSUE THREAD

**Issue by Wesley-Guoxy** [BryanChiu/Mactivision#117]
## Description:
I have some ideas about the UI design of the first mini game. As shown below, I am digging a hole to possibly mine good treasure for myself. The digging process is shown by many frames of animation, which is helpful for players to understand what they are doing. But the color of undeveloped soil is almost the same of background of the hole, in which case I get confused and mistakenly think that the cute character is floating in the air. I suggest changing the color combination of the UI design. 

## Environment:
Windows10, Python3.7.9, Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:

![image](https://user-images.githubusercontent.com/42874340/110312066-94a3f480-803f-11eb-8e63-7101467812e8.png)
![image](https://user-images.githubusercontent.com/42874340/110312072-97064e80-803f-11eb-814b-889dc54296d2.png)

 
## Expected Result:
Suitable color combination of UI design

## Severity: 
LOW

**Comment by BryanChiu** [comment]
Will make changes
