### ISSUE TITLE
Early exit of the first mini game

### ISSUE THREAD

**Issue by Wesley-Guoxy** [BryanChiu/Mactivision#118]
## Description:
I am in the middle of the first mini game while being busy to check the result log of the console and internet requests, at which time the game jump right to the end and tell me that I have got the treasure. As shown below, I have no idea where the big treasure is.

## Environment:
Windows10, Python3.7.9, Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:
1.	start playing
2.	wait for some time and do something else with the browser’s developer tools
3.	boom! jump to the end of the game
![image](https://user-images.githubusercontent.com/42874340/110312218-c321cf80-803f-11eb-8529-5a71670aa8fa.png)

## Expected Result:
I should be able to continue playing the game even after a long interval 

## Severity: 
HIGH

**Comment by BryanChiu** [comment]
We'll add a "MaxGameTime" config value for Digger, so the game time limit is up to the researcher (config file writer).

**Comment by BryanChiu** [comment]
Duplicate of https://github.com/BryanChiu/Mactivision/issues/77
