### ISSUE TITLE
Compatibility Test

### ISSUE THREAD

**Issue by Wesley-Guoxy** [BryanChiu/Mactivision#119]
## Description:
I am testing functionality on mobile devices, but first I try to open main page by the web browser embedded in WeChat PC application, which is the most popular communication application in China. Suppose that we need to share the mini game with our families or friends, it would be very convenient if others open up through chatting app. Unfortunately, our mini game won’t work at all on the browser provided by WeChat PC application.

## Environment:
Windows10, Python3.7.9

## Steps to Reproduce:
1.	Send http://127.0.0.1:3000 to any contact through WeChat window
2.	The situation happens like below
![image](https://user-images.githubusercontent.com/42874340/110314655-1a756f00-8043-11eb-9f19-9dbda5fc5539.png)

## Expected Result:
Run the web application anywhere we want.

## Severity: 
MIDDLE

**Comment by DavidHospital** [comment]
This is out of the scope of this project. Our project is not intended to work on modile devices, and end users should not be send the link to other people. Furthermore, if WeChat internal browser does not support WebAssembly, there is nothing we can do to fix that.
