### ISSUE TITLE
Gaming window won't automatically resize

### ISSUE THREAD

**Issue by Wesley-Guoxy** [BryanChiu/Mactivision#120]
## Description:
It always happens when I press F12 to quit debugging, the main page keep still and won’t scale to the right size. Only after a long waiting can I have the full screen size of the game.

## Environment:
Windows10, Python3.7.9, Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:
1.	visit game page
2.	open developer tool panel
3.	close the tool panel, and you will see
 ![image](https://user-images.githubusercontent.com/42874340/110316112-3aa62d80-8045-11eb-92b5-1c69e79effda.png)

## Expected Result:
The gaming window resize to normal width after closing the developer tool panel

## Severity: 
LOW

**Comment by Cmon16** [comment]
Duplicate to #81

**Comment by teemh** [comment]
Fixed with responsive template.
