### ISSUE TITLE
Parameter settings

### ISSUE THREAD

**Issue by Wesley-Guoxy** [BryanChiu/Mactivision#122]
## Description:
I am trying to adjust game parameters and I set “MaxFoodDispensed” to 5 but leave “TotalFoods” unchanged, which is 6. It is obvious that the monster can not be fully fed with only 5 food items condition on that it will be fed with at least 6 food items. This kind of configuration is logically wrong and should be avoided, but no such kind of logic examination currently. 

## Environment:
Windows10, Python3.7.9, Microsoft Edge version 89.0.774.45 (64-bit)

## Steps to Reproduce:
1.	set “MaxFoodDispensed” a number less than “TotalFoods”
 
![image](https://user-images.githubusercontent.com/42874340/110332593-7d730000-805b-11eb-9a7f-7277266cb6e5.png)

2.	keep playing the second mini game and you will always get such kind of result
 
![image](https://user-images.githubusercontent.com/42874340/110332599-806df080-805b-11eb-9c21-f7b5c6545b19.png)

## Expected Result:
Some game parameters should be strictly constrained by others

## Severity: 
MIDDLE

**Comment by BryanChiu** [comment]
Documentation possibly unclear. “MaxFoodDispensed” is the number of foods dispensed before the game ends. “TotalFoods” is the number of unique foods (hotdog, hamburger, pizza, etc) used in the current game.

**Comment by BryanChiu** [comment]
[Configuration documentation](https://github.com/BryanChiu/Mactivision/wiki/Mini%E2%80%90Games-Configurations) updated
