### ISSUE TITLE
The Feeder mission always shows the same message

### ISSUE THREAD

**Issue by behdadkha** [BryanChiu/Mactivision#57]
# Title
The Feeder mission always shows the same message.

# Environment
Windows desktop,
Browser: Chrome

# Steps to reproduce 
Discard all the foods and don't feed the monster.

# Expected result
The dialog should say something like "The monster died" because he was hungry for so long.

# Actual result
The dialog says "The monster has been well fed!".

# Severity
MEDIUM

**Comment by DavidHospital** [comment]
This is out of the scope of our project; there is no "lose" condition which the minigame has to report to the player.
