### ISSUE TITLE
The fireworks in the Rockstar game doesn't cause any damage.

### ISSUE THREAD

**Issue by behdadkha** [BryanChiu/Mactivision#58]
# Title
The fireworks in the Rockstar game doesn't cause any damage.

# Description
In the introduction part of the Rockstar game, it says too much fireworks is dangerous, but nothing dangerous happens if I keep holding "L" during the entire game.

# Environment
Windows desktop,
Browser: Chrome

# Steps to reproduce 
Keep holding the "L" key during the Rockstar game.

# Expected result
The scene or the artist should get on fire.

# Actual result
Nothing dangerous happens if I keep holding "L".

# Severity
MEDIUM

**Comment by DavidHospital** [comment]
This issue is invalid, as user should not be given too much feedback, otherwise it will be too easy for them to multitask, and the recorded data will be invalid.

**Comment by BryanChiu** [comment]
[Game description](https://github.com/BryanChiu/Mactivision/blob/master/README.md) updated
