### ISSUE TITLE
First dig level is not time sensitive

### ISSUE THREAD

**Issue by mudarthc** [BryanChiu/Mactivision#59]
**Bug** : The instruction state "dig as fast as you can" however the user can take their time and they never have any pressure.. ie they always win. I think it would be alot more fun if there was a timer similar to a traditional game ( a ui feature to add/ usability issue).
**Steps**: 
1. Start game 
2. at first level take as much time as you want to dig

**Environment**: Mac os

**Expected**:  expected a timer or a game like environment

**Actual**: no timer or lose situation

**Comment by DavidHospital** [comment]
This is out of the scope of our project; the player cannot "win", these minigames are meant to record a user's abilities, not provide user with fun experience.
