### ISSUE TITLE
third level (with the spotlight) user wins regardless of actions

### ISSUE THREAD

**Issue by mudarthc** [BryanChiu/Mactivision#62]
**Bug** :  I pressed no keys in the third level causing the spot light not to move, this resulted in me still winning the level

**Steps**: simply navigate to third level and press no buttons when level begins
 https://drive.google.com/file/d/1ZhkLQRkP4bBnZ_kGeLqvgSh3BG4A0Ol4/view?usp=sharing

**Environment**:  macOS

**Expected**:  Expected for me to lose and the audience sidebar to go down because i was not following the instructions of moving the spotlight on the character

**Actual**: This was not the case, instead i won the level and the message said "great show", I believe that this was timed and regardless of the users input the player will still win.

**Comment by DavidHospital** [comment]
This is out of the scope of our project; the player cannot "win", these minigames are meant to record a user's abilities, not provide user with fun experience.

**Comment by mudarthc** [comment]
that makes sense, but to record the users ability wouldn't it require the user to press keys and follow the given instructions?

**Comment by mudarthc** [comment]
i see, however maybe its a bit misleading having "winning" conformations after each level, indicating to the user the completed the game correctly when in fact they didn't (ie didn't press any buttons as mentioned above)

**Comment by BryanChiu** [comment]
[Game description](https://github.com/BryanChiu/Mactivision/blob/master/README.md) updated
