### ISSUE TITLE
sidebar in spotlight level doesnt work

### ISSUE THREAD

**Issue by mudarthc** [BryanChiu/Mactivision#63]
**Bug** : Even if you follow the avatar with the spotlight (as instructed) the sidebar still starts at the top sinks to the bottom and remains at zero the entire game. The sidebar (pictured below)
 is supposed to measure if you are following the instructions and keeping the audience entertained.
![Screen Shot 2021-02-25 at 3 16 37 PM](https://user-images.githubusercontent.com/35268733/109211659-7eaf4d80-777c-11eb-8043-fdf18ef1254f.png)
**Environment**:  MacOS

**Expected**:  Expected the sidebar to fluctuate based on if i was following the avatar correctly or not

**Actual**: seemed to be pre programmed to start at 100 and go to zero, only changed if fireworks are lit. There is really no gage of if you are doing well or not in this level.

**Comment by DavidHospital** [comment]
Documentation was unclear; meter and spotlight do not interact with each other. Documentation needs to be updated to explain the mechanics of this minigame more clearly

**Comment by mudarthc** [comment]
Not sure if the invalid tag was added by mistake if the documentation is unclear.

**Comment by BryanChiu** [comment]
[Game description](https://github.com/BryanChiu/Mactivision/blob/master/README.md) updated
