### ISSUE TITLE
Maximize button not visible without scrolling

### ISSUE THREAD

**Issue by SamCymbaluk** [BryanChiu/Mactivision#66]
Steps to reproduce:
- Start client and server
- Navigate to localhost:3000

Expected results:
- The maximize button is visible and can be clicked

Actual results:
- The user has to scroll to see the maximization button, which makes it easy to miss

**Comment by teemh** [comment]
The is caused by the default size of the game in the browser. We set the size to smaller than the most common resolution 1920x1080 but we can examine making it smaller by default. However, the maximize button is created by the unity itself and we cannot move it.

**Comment by DavidHospital** [comment]
This is out of the scope of this project
