### ISSUE TITLE
No way to exit game in progress

### ISSUE THREAD

**Issue by SamCymbaluk** [BryanChiu/Mactivision#67]
Steps to reproduce:
- Start client and server
- Navigate to localhost:3000
- Click start battery

Expected results:
- There is a way to exit a game without closing the webpage (see SRS 2.2/mini-games)

Actual results:
- The only option is to continue playing or close the browser window

**Comment by DavidHospital** [comment]
Currently if a minigame is terminated unexpectedly, the server receives no feedback. We need to implement some functionality for the server to invalidate a battery session if it doesn't received any requests after a given time. After this functionality is implemented, we can add exit options in minigames, which will send a request to the server to invalidate the current session.

**Comment by teemh** [comment]
We don't want the users to accidentally close a game during testing. If they really want to close the game they can close their tab/browser. Users don't need to be able pick games so exiting isn't important.
