### ISSUE TITLE
Digger games records more button presses than registered by game

### ISSUE THREAD

**Issue by SamCymbaluk** [BryanChiu/Mactivision#69]
Steps to reproduce:
* Start client and server
* Navigate to localhost:3000
* Play digger and click as a quick as possible
* Complete remainder of the battery
* Open digger_{id}.json from battery run

Expected results:
* The number of recorded button presses should be `2*DigAmount` as that is the number of up+down clicks required to get to the treasure

Actual results:
* The number of recorded button presses far exceeds `2*DigAmount`

**Comment by DavidHospital** [comment]
@SamCymbaluk can you paste the config file you used to produce this issue, as well as both the outputted json files the digger game produced (digger & config)? Thanks

**Comment by BryanChiu** [comment]
Digger mechanic changed. Metric can record more presses than `DigAmount`, intentional, won't fix
