### ISSUE TITLE
Request: End of Game Options

### ISSUE THREAD

**Issue by coffeexcode** [BryanChiu/Mactivision#70]
Possibly include the following on the final screen
1. Replay button to replay the game without close and restarting the game.
2. A score summary. Something similar like:
   a) Time to dig
   b) % correct on monster feeding
   c) % time with correct spotlight position

**Comment by DavidHospital** [comment]
This is invalid: Score should not be provided to user, and game should not be replayable, as that would disrupt the battery. Documentation should be updated to better explain that these minigames are gamificationized tests.

**Comment by BryanChiu** [comment]
[Project and game descriptions](https://github.com/BryanChiu/Mactivision/blob/master/README.md) updated
