### ISSUE TITLE
Feeder game does not respect maximum time limit

### ISSUE THREAD

**Issue by coffeexcode** [BryanChiu/Mactivision#71]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Start the application client and server
2. Navigate to the game page
3. Complete the first level
4. Sit idle after starting the feeder game

### Expected:
After the time limit, the game should automatically end.

### Actual:
Nothing happens. The game continues after exceeding the limit set in Battery.json

#### Notes
I left the Battery.json as default and timed the game. After 3minutes, the game did not end automatically (default game time is 90 seconds)

**Comment by coffeexcode** [comment]
The game will actually end if you wait past the time and perform one action, but will stay in game indefinitely if you do not perform an action.

**Comment by BryanChiu** [comment]
Will change to game ending immediately. Will add line to Feeder and Digger output metric json to say if game ended because "MaxGameTime" reached
