### ISSUE TITLE
Feeder game crashes when "TotalFoods" is still within accepted boundaries

### ISSUE THREAD

**Issue by coffeexcode** [BryanChiu/Mactivision#72]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Edit Battery.json field "TotalFoods" and set the value to 1.
1. Start the application client and server
2. Navigate to the game page
3. Complete the first level
4. Play the second level

### Rational
The Testing document stipulates that the value for "TotalFoods" should be between 1 and 7 inclusive. I selected a value of 1 and the game crashed anyways.

### Expected:
The game should still be playable

### Actual:
Game crashes and chrome suggests killing the page.

### Screenshot
![image](https://user-images.githubusercontent.com/13461008/109362204-82b09d80-7858-11eb-8bcb-f89a7c60661b.png)

**Comment by DavidHospital** [comment]
fix infinite while loop at https://github.com/BryanChiu/Mactivision/blob/master/Mactivision%20Mini-Games/Assets/Scripts/Feeder/Dispenser.cs#L129-L132
