### ISSUE TITLE
Not all keys are allowed for digger game

### ISSUE THREAD

**Issue by alishahimtiaz** [BryanChiu/Mactivision#73]
Steps to reproduce:

Start client and server
Edit input/Battery.json to Esc key.
Navigate to localhost:3000
Click start battery

Expected results:

The title screen should say "Press Esc to dig"

Actual results:

Escape key does not work when digging. Key stays static at "B"

**Comment by DavidHospital** [comment]
Documentation links to valid [Unity KeyCodes](https://docs.unity3d.com/ScriptReference/KeyCode.html). In this case, "Escape" should have been used.
