### ISSUE TITLE
Dig amount when negative sets to default 100.

### ISSUE THREAD

**Issue by alishahimtiaz** [BryanChiu/Mactivision#74]
Steps to reproduce:

Start client and server
Edit Dig Amount in input/Battery.json to -1.
Navigate to localhost:3000
Click start battery

Expected results:

The spec says it rounds to multiples of 10. 10 should mean each keystroke digs a hole, for a total of 10 keystrokes to reach the end.

Actual results:

I have to press 100 times to reach the treasure, so the rounding does not work when negative. Perhaps the abs value should be used instead of setting the default to 100.

**Comment by DavidHospital** [comment]
This is the intended result. Documentation should be updated to make this clear.

**Comment by BryanChiu** [comment]
[Configuration documentation](https://github.com/BryanChiu/Mactivision/wiki/Mini%E2%80%90Games-Configurations) updated
