### ISSUE TITLE
Time can be negative for Feeder, but nothing happens

### ISSUE THREAD

**Issue by alishahimtiaz** [BryanChiu/Mactivision#75]
Steps to reproduce:

Start client and server
Edit input/Battery.json to negative time for Feeder Confg MaxGameTime.
Navigate to localhost:3000
Click start battery

Expected results:
The loading screen should be greyed out and say invalid parameter.

Actual results:

Doesn't change the time for the game.

**Comment by DavidHospital** [comment]
This is working as intended: any invalid values put in a config file will be changed to their respective default values. Documentation should be updated to reflect this.

**Comment by BryanChiu** [comment]
[Configuration documentation](https://github.com/BryanChiu/Mactivision/wiki/Mini%E2%80%90Games-Configurations) updated
