### ISSUE TITLE
[Digger game] level complete without pressing any key

### ISSUE THREAD

**Issue by FangY2019** [BryanChiu/Mactivision#77]
In the digger game, even the user did not dig, the level complete information will be shown finally.

## Environment
Device: ASUS Laptop
OS:Windows 10
Browser: Google Chrome

## Steps to Reproduce:
1. Start Battery
2. Press "B" to go digger 
3. do not do anything and wait for few minutes

## Expected: 
Information for time out

## Actual: 
Level Complete

## Screenshot
![Capture2](https://user-images.githubusercontent.com/54195303/109610270-895e3f80-7afa-11eb-993f-d02e9861ad6c.PNG)

**Comment by DavidHospital** [comment]
This is the intentional behaviour. We will update end screen message to indicate user's time has ran out.
