### ISSUE TITLE
Failing to load libraries

### ISSUE THREAD

**Issue by coffeexcode** [BryanChiu/Mactivision#78]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Start the application client and server
2. Navigate to the game page

### Expected:
The game loads

### Actual:
An error occurs preventing the game from loading

### Screenshot
![image](https://user-images.githubusercontent.com/13461008/109903256-90579000-7c69-11eb-87a0-49c5d6eee423.png)

#### Notes
This is 5 days after last testing, no changes to any files.

**Comment by coffeexcode** [comment]
Re downloaded the linked artifact, followed setup instructions with fresh files. Same error. 
No errors reported in python.

![image](https://user-images.githubusercontent.com/13461008/109903577-f3492700-7c69-11eb-9068-58bf372bd52f.png)

**Comment by DavidHospital** [comment]
In your first screenshot, the url in your brower is pointing to the `index.html` file. The instructions say to start the client and server and then navigate to `127.0.0.1:3000`. Navigating to the `index.html` file will not start the game correctly.
