### ISSUE TITLE
Was able to pass the rockstar game without pressing a or d keys.

### ISSUE THREAD

**Issue by robertjvardy** [BryanChiu/Mactivision#80]
Steps to reproduce:
- initiate game involving the rockstar
- exclusively press l key to keep the bar in the white area.

Expected: level should be failed or some negative consequence
Actual: level is passed

**Comment by DavidHospital** [comment]
This is the intended result. These tests are disguised as minigames, and should not provide this sort of feedback to users, as it could invalidate data collected from future minigames in the battery.
