### ISSUE TITLE
No scaling support for smaller screens

### ISSUE THREAD

**Issue by coffeexcode** [BryanChiu/Mactivision#81]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Start the application client and server
2. Navigate to the game page with a smaller device screen

### Expected:
The game loads into the window size

### Actual:
The game loads off screen

### Screenshot
![image](https://user-images.githubusercontent.com/13461008/109905551-f560b500-7c6c-11eb-8379-06deaefdbb04.png)

**Comment by teemh** [comment]
Should be fixed.
