### ISSUE TITLE
Not feeding the monster still results in message: The monster has been fed well

### ISSUE THREAD

**Issue by robertjvardy** [BryanChiu/Mactivision#84]
Steps to reproduce:
- run the app as instructed
- navigate to the monster level
- do not feed the monster

Expected: Message corresponding to the players actions should be displayed after the game has concluded
Actual: Message "The monster has been fed well" is displayed

Severity: medium
priority: medium

**Comment by DavidHospital** [comment]
Duplicate of https://github.com/BryanChiu/Mactivision/issues/57

**Comment by BryanChiu** [comment]
https://github.com/BryanChiu/Mactivision/issues/57 closed
