### ISSUE TITLE
[Rockstar] can not go back to the previous instruction

### ISSUE THREAD

**Issue by FangY2019** [BryanChiu/Mactivision#85]
There are more than one instruction in the Rock game, the user can not go back to have a look at the previous instruction if they forget which keys they should use in the game.

## Environment
Device: ASUS Laptop
OS:Windows 10
Browser: Google Chrome

## Steps to Reproduce:
1. Start Battery
2. Play the 3rd game(Rockstar) 

## Expected Result
Users could go back to have a look at the previous instruction. 

## Actual Result: 
Not allow to go back to the previous instruction.

## Severity
LOW

**Comment by DavidHospital** [comment]
Will be fixed in https://github.com/BryanChiu/Mactivision/issues/79
