### ISSUE TITLE
Background Flickering After Exiting Full Screen Game play

### ISSUE THREAD

**Issue by immanuel-odisho** [BryanChiu/Mactivision#87]
Repro:
1. Open Game and run on Google Chrome Browser using Linux Based OS
2. Play Game in full screen mode
3. Exit Game

Observation:
Game has background flickering or background isnot fully recovered from full screen mode.

Expectation:
Browser should return to normal after exiting recovery mode.
![Screenshot from 2021-03-04 10-46-14](https://user-images.githubusercontent.com/35702189/109990310-45746180-7cd7-11eb-8b0a-771c94a7909d.png)
![Screenshot from 2021-03-04 10-45-11](https://user-images.githubusercontent.com/35702189/109990314-460cf800-7cd7-11eb-9438-8b1bd6e04889.png)

**Comment by teemh** [comment]
Fixed with responsive template.
