### ISSUE TITLE
Dig not working when DigAmount set to 100000

### ISSUE THREAD

**Issue by immanuel-odisho** [BryanChiu/Mactivision#88]
Repro:
1. Edit the configuration file
2. Set DigAmount to 100000
3. Play Game

Observation:
Dig does not work at all
Expect:
Dig to reset to some default value or be functional in some way

**Comment by DavidHospital** [comment]
I tested this and the first block was advanced to the first dig frame after 1000 presses. It works as intended.

**Comment by immanuel-odisho** [comment]
I tested this locally and it still does not work? How are you testing it and how are you keeping track of your presses?

**Comment by BryanChiu** [comment]
After 1000 valid key presses, you should see the first block advance to the first break animation.
![image](https://user-images.githubusercontent.com/25440765/111006486-dfcd4880-835a-11eb-956e-4aa779481589.png)

**Comment by immanuel-odisho** [comment]
Afterwards it does not change to another animation. Are you able to complete the level with the digAmount specified?

**Comment by BryanChiu** [comment]
You have to press it another 1000 times to advance to the second break animation. In theory, 100000 presses will get the character to the bottom.

**Comment by immanuel-odisho** [comment]
Hi Bryan, 

I tried to do that but the animaton does not change. In other words, if the DigAmount is set to a high enough value the user cannot complete the level.

**Comment by BryanChiu** [comment]
I got to the third break animation (>3000 presses) before coming to the conclusion that 100000 is not too large of a number. However there is a [limit](https://github.com/BryanChiu/Mactivision/issues/89), but then the Battery cannot even be started.
