### ISSUE TITLE
Game Crashes if DigAmount set to a large value

### ISSUE THREAD

**Issue by immanuel-odisho** [BryanChiu/Mactivision#89]
Repro:
1. Edit Config file and set DigAmount to 100000000000000000000
2. run Game

Observations:
Game Crashes and does not work
![Screenshot from 2021-03-04 10-57-04](https://user-images.githubusercontent.com/35702189/109991573-6d17f980-7cd8-11eb-9656-b231e1107734.png)

Expectation:
Game should work since the documentation says DigAmount can be anything over 100

**Comment by BryanChiu** [comment]
Will explain in documentation that large values could result in parse errors.

**Comment by BryanChiu** [comment]
[Configuration documentation](https://github.com/BryanChiu/Mactivision/wiki/Mini%E2%80%90Games-Configurations) updated
