### ISSUE TITLE
MaxFoodDispensed set to large natural number (as per documentation) causes game to crash

### ISSUE THREAD

**Issue by immanuel-odisho** [BryanChiu/Mactivision#91]
Repro:
1. Set MaxFoodDispensed to 10000000000 in config file
2. Play Game

Observation:
Game Crashes
Expectation:
Game should work or reset to default value. According to documentation it says any natural number should work.
![Screenshot from 2021-03-04 11-04-51](https://user-images.githubusercontent.com/35702189/109992667-7bb2e080-7cd9-11eb-8eeb-f0ee9024ee0f.png)

**Comment by BryanChiu** [comment]
Will explain in documentation that large values could result in parse errors.

**Comment by BryanChiu** [comment]
[Configuration documentation](https://github.com/BryanChiu/Mactivision/wiki/Mini%E2%80%90Games-Configurations) updated
