### ISSUE TITLE
AverageUpdateFrequency set to low makes Level 2 Impossible to complete

### ISSUE THREAD

**Issue by immanuel-odisho** [BryanChiu/Mactivision#92]
Repro:
1. Change AverageUpdateFrequency to 0.001
2. Play Level 2

Observation:
It is impossible to complete the level since Food is always updated but not being outputted to be fed to monster making ti impossible to complete
Expectation:
Some workaround for users to skip or complete this if they get stuck

**Comment by DavidHospital** [comment]
@immanuel-odisho I am a bit confused on what is being reported in this issue, Could you please elaborate? I was able to complete the feeder game with `AverageUpdateFrequency = 0.001` with no issues.

**Comment by immanuel-odisho** [comment]
If you set the AverageUpdateFrequency to a low enough value, the food is updating every round. This makes it impossible to get the opportunity to feed the Monster the correct food and makes it impossible to win the round.

**Comment by DavidHospital** [comment]
I understand. In actuality, the user is not required to feed the monster each good that flashes green. The user is meant to only feed foods that the monster currently likes. So if a food flashes green, it is added to the set of foods the monster likes, and if it flashes red, it is removed from that set. Additionally, this minigame will be used to test a user's memory, so the user is not required to "win" the game, as there is no such thing. They are only required to do their best, so their cognitive abilities can be mesured accuratly. I will mark this as documentation, as we believe our documentation was not clear enough in this regard.

**Comment by BryanChiu** [comment]
[Game description](https://github.com/BryanChiu/Mactivision/blob/master/README.md) updated
