### ISSUE TITLE
Spotlight disappears if Config values set to high values

### ISSUE THREAD

**Issue by immanuel-odisho** [BryanChiu/Mactivision#93]
Repro:
1. Edit config file and change the values to the ones shown in the attached image
2. Play the Game

Observation:
Spotlight disappears
Expectation:
Values should default to some default value or work in some way since according to the documentation these are valid values
![Screenshot from 2021-03-04 11-25-06](https://user-images.githubusercontent.com/35702189/109995464-4eb3fd00-7cdc-11eb-81cf-8fede788c4b3.png)

**Comment by BryanChiu** [comment]
Will put upper bound on some config values, and change documentation accordingly.

**Comment by BryanChiu** [comment]
[Configuration documentation](https://github.com/BryanChiu/Mactivision/wiki/Mini%E2%80%90Games-Configurations) updated
