### ISSUE TITLE
Cannot move character after using valid configuration

### ISSUE THREAD

**Issue by immanuel-odisho** [BryanChiu/Mactivision#94]
Repro:
1. Use the config attached below
2. Play level 3 in game
3.Click on "A" or "D"
![Screenshot from 2021-03-04 11-25-06](https://user-images.githubusercontent.com/35702189/109995707-88850380-7cdc-11eb-8072-6e9cfdd70e4c.png)

Observation:
Character cannot move
Expectation:
Character should be able to move

**Comment by BryanChiu** [comment]
Player is not supposed to be able to control character. Duplicate issue as https://github.com/BryanChiu/Mactivision/issues/93

**Comment by immanuel-odisho** [comment]
I think this issue is valid and it is not a duplicate. This issue should be reopened. The #93 issue is about the splotlight disappearing. This issue is about the character not being able to move the character. If the default configuration used the character is able to move. Once these configurations are the set, the player is no longer able to move and it breaks the game. There should be some error handling to handle this case or else the player is stuck and unable to play the game.
