### ISSUE TITLE
Fireworks functionality breaks the 3rd minigame

### ISSUE THREAD

**Issue by Jailoodu** [BryanChiu/Mactivision#95]
**Summary**: One can constantly press or hold the `L` button to trigger the fireworks in the final game. This causes the audience hype to rise to the top without delay.

**Visual proof**:
![image](https://user-images.githubusercontent.com/21979292/110216156-86a57680-7e7b-11eb-9903-65ca151cd711.png)

**Expected result**: One should not be able to hold down the `L` button to trigger the fireworks. It should get harder for the audience hype to rise as it increases.

**Actual result**: It is very easy for the audience hype to rise by holding or clicking the `L` button.

**Steps to reproduce**:

1. Run the program provided and finish the first 2 games.
2. On the third game, just hold down the `L` button until the `Level Complete` appears.

**Environment**: Microsoft Windows 10 Home, Google Chrome

**Severity**: Medium
**Priority**: Medium

**Comment by BryanChiu** [comment]
It is the job of the player to not let the meter get too high/low. Instructions will be updated

**Comment by BryanChiu** [comment]
[Game description](https://github.com/BryanChiu/Mactivision/blob/master/README.md) updated
