### ISSUE TITLE
Debug console is unavailable when using responsive modes

### ISSUE THREAD

**Issue by Jailoodu** [BryanChiu/Mactivision#97]
**Summary**: The debug console function should appear on the main screen but it doesn't when playing the game in a mode that resizes the screen.

**Visual proof**:
![image](https://user-images.githubusercontent.com/21979292/110221603-27575e80-7e9b-11eb-85d3-9e29ae02f728.png)

**Expected result**: The debug console should be accessible on the left hand side of the screen.

**Actual result**: The debug console functionality option is not present.

**Environment**: Microsoft Windows 10 Home, Google Chrome

**Severity**: Low
**Priority**: Low

**Comment by Cmon16** [comment]
Duplicate to #68

**Comment by BryanChiu** [comment]
https://github.com/BryanChiu/Mactivision/issues/68 closed
