### ISSUE TITLE
Cannot Play Digger Minigame in Full Screen when Dig Button is Escape Character

### ISSUE THREAD

**Issue by syed-razi** [BryanChiu/Mactivision#98]
### Description:
I set the Dig key to the escape character and noticed that when I'm in full screen, pressing escape escapes the screen rather than perform digging.

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open Battery.json
2. Set DigKey to `"Escape"`
3. Start Client and Server
4. Enter full screen
5. Press escape to dig

### Actual Result:

Full screen minimizes to windowed mode when pressing escape rather than digging

### Expected Result:

I would expect the Escape key to not be assignable as the dig key

### Suggestion

Remove Escape key as an option to be one of the assignable keys

**Comment by BryanChiu** [comment]
We will only allow certain keys.
