### ISSUE TITLE
String representation of Integer Allowed for DigAmount

### ISSUE THREAD

**Issue by syed-razi** [BryanChiu/Mactivision#99]
### Description:
I noticed that setting the DigAmount to a string representation of an integer works just like an integer. This does not seem to be intended from the instructions on editing the configuration file:
![image](https://user-images.githubusercontent.com/25377291/110268365-85fe0480-7f8f-11eb-88fa-0b0040fa7584.png)

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open Battery.json
2. Set DigAmount to `"10"`
![image](https://user-images.githubusercontent.com/25377291/110268311-72eb3480-7f8f-11eb-9613-4e19d1c3611b.png)
3. Save file
3. Start Client and Server
4. Dig normally

### Actual Result:

Digging works similarly to when DigAmount is set using an integer

### Expected Result:

I would have expected this to fail or to get some sort of warning, or for the instructions to mention that strings are allowed

### Severity: Low

**Comment by BryanChiu** [comment]
This is working as intended; the game will cast any value to the intended type (in this case the string "10" is cast to a integer 10)
